// =========================================================== Signup Form Types
export const MOVE_SIGNUP_FORM_FORWARD = "MOVE_SIGNUP_FORM_FORWARD";
export const MOVE_SIGNUP_FORM_BACKWARD = "MOVE_SIGNUP_FORM_BACKWARD";
export const CREATE_NEW_ACCOUNT_START = "CREATE_NEW_ACCOUNT_START";
export const CREATE_NEW_ACCOUNT_SUCCESS = "CREATE_NEW_ACCOUNT_SUCCESS";
export const CREATE_NEW_ACCOUNT_ERROR = "CREATE_NEW_ACCOUNT_ERROR";
export const CREATE_NEW_CHARITY_START = "CREATE_NEW_CHARITY_START";
export const CREATE_NEW_CHARITY_SUCCESS = "CREATE_NEW_CHARITY_SUCCESS";
export const CREATE_NEW_CHARITY_ERROR = "CREATE_NEW_CHARITY_ERROR";
export const UPDATE_SIGNUP_FORM = "UPDATE_SIGNUP_FORM";
export const UPDATE_DONOR_FORM = "UPDATE_DONOR_FORM";
export const UPDATE_CHARITY_FORM = "UPDATE_CHARITY_FORM";
export const CLOSE_SIGNUP_MODAL = "CLOSE_SIGNUP_MODAL";

// =========================================================== Login Form Types
export const LOGIN_APP_START = "LOGIN_APP_START";
export const LOGIN_APP_SUCCESS = "LOGIN_APP_SUCCESS";
export const LOGIN_APP_ERROR = "LOGIN_APP_ERROR";
export const LOGIN_CHARITY_START = "LOGIN_CHARITY_START";
export const LOGIN_CHARITY_SUCCESS = "LOGIN_CHARITY_SUCCESS";
export const LOGIN_CHARITY_ERROR = "LOGIN_CHARITY_ERROR";
export const LOGOUT_APP = "LOGOUT_APP";
export const UPDATE_LOGIN_FORM = "UPDATE_LOGIN_FORM";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";
export const EXPIRED_CREDENTIALS = "EXPIRED_CREDENTIALS";
export const LOGIN_TOKEN_START = "LOGIN_TOKEN_START";
export const LOGIN_TOKEN_SUCCESS = "LOGIN_TOKEN_SUCCESS";
export const LOGIN_TOKEN_ERROR = "LOGIN_TOKEN_ERROR";
export const LOGIN_TOKEN_CHARITY_START = "LOGIN_TOKEN_CHARITY_START";
export const LOGIN_TOKEN_CHARITY_SUCCESS = "LOGIN_TOKEN_CHARITY_SUCCESS";
export const LOGIN_TOKEN_CHARITY_ERROR = "LOGIN_TOKEN_CHARITY_ERROR";

// =========================================================== Donor Types
export const FETCH_USER_DONATIONS_START = "FETCH_USER_DONATIONS_START";
export const FETCH_USER_DONATIONS_SUCCESS = "FETCH_USER_DONATIONS_SUCCESS";
export const FETCH_USER_DONATIONS_ERROR = "FETCH_USER_DONATIONS_ERROR";
export const FETCH_CHARITIES_START = "FETCH_CHARITIES_START";
export const FETCH_CHARITIES_SUCCESS = "FETCH_CHARITIES_SUCCESS";
export const FETCH_CHARITIES_ERROR = "FETCH_CHARITIES_ERROR";
export const SELECT_DONATIONS = "SELECT_DONATIONS";
export const SELECT_CHARITIES = "SELECT_CHARITIES";
export const SELECT_CHARITY = "SELECT_CHARITY";
export const CARD_PAYMENT_START = "CARD_PAYMENT_START";
export const CARD_PAYMENT_SUCCESS = "CARD_PAYMENT_SUCCESS";
export const CARD_PAYMENT_ERROR = "CARD_PAYMENT_ERROR";
export const CLOSE_PAYMENT_MODAL = "CLOSE_PAYMENT_MODAL";
export const HANDLE_PAYMENT_FORM = "HANDLE_PAYMENT_FORM";
export const HANDLE_CARD_TOKEN_ERROR = "HANDLE_CARD_TOKEN_ERROR";

//============================================================ Charity Types
export const FETCH_CHARITY_DONATIONS_START = "FETCH_CHARITY_DONATIONS_START";
export const FETCH_CHARITY_DONATIONS_SUCCESS =
  "FETCH_CHARITY_DONATIONS_SUCCESS";
export const FETCH_CHARITY_DONATIONS_ERROR = "FETCH_CHARITY_DONATIONS_ERROR";
