// =========================================================== Signup Form Types
export const MOVE_SIGNUP_FORM_FORWARD = "MOVE_SIGNUP_FORM_FORWARD";
export const MOVE_SIGNUP_FORM_BACKWARD = "MOVE_SIGNUP_FORM_BACKWARD";
export const CREATE_NEW_ACCOUNT_START = "CREATE_NEW_ACCOUNT_START";
export const CREATE_NEW_ACCOUNT_SUCCESS = "CREATE_NEW_ACCOUNT_SUCCESS";
export const CREATE_NEW_ACCOUNT_ERROR = "CREATE_NEW_ACCOUNT_ERROR";
export const CREATE_NEW_CHARITY_START = "CREATE_NEW_CHARITY_START";
export const CREATE_NEW_CHARITY_SUCCESS = "CREATE_NEW_CHARITY_SUCCESS";
export const CREATE_NEW_CHARITY_ERROR = "CREATE_NEW_CHARITY_ERROR";
export const UPDATE_SIGNUP_FORM = "UPDATE_SIGNUP_FORM";
export const UPDATE_DONOR_FORM = "UPDATE_DONOR_FORM";
export const CLOSE_SIGNUP_MODAL = "CLOSE_SIGNUP_MODAL";

// =========================================================== Insert More as Needed
